apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-todo
  template:
    metadata:
      labels:
        app: django-todo
    spec:
      containers:
      - name: django-todo
        image: arulselvan22/django-todo:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-todo-service
spec:
  selector:
    app: django-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
